### ISSUE TITLE
[invader-build] Some aspects of scenario scripts can fail to function correctly when a map is built with invader-build.

### ISSUE THREAD

**Issue by Vaporeon** [Kavawuvi/invader#46]
One example is the beginning of b40. While scripts work enough to play through the level, the sleeping grunts in the opening cut-scene are not removed when they should be.

**Comment by Kavawuvi** [comment]
There seems to be a similar issue with the issue https://github.com/Kavawuvi/Invader/issues/25 where it softlocks the game on a10.map if you don't make it to the door before the crewman does.

After doing some testing, I can confirm that it is not the script block itself. After implementing command lists (https://github.com/Kavawuvi/Invader/commit/3631ebb9c751dee0947bfbe0aba509fc5af79757) I noticed that the sleeping grunts are now removed. That said, when watching the cutscene using the debug camera, they are teleported out of the room instead of actually running out of the room into the door. Also, once you exit the pelican, the door opens automatically as expected, but the elite stays in the hallway.

From the looks of things, it may be one a firing position issue.

**Comment by Kavawuvi** [comment]
There seems to be a similar issue with the issue https://github.com/Kavawuvi/Invader/issues/25 where it softlocks the game on a10.map if you don't make it to the door before the crewman does.

After doing some testing, I can confirm that it is not the script block itself, as directly copying the script syntax block from a known working map (one built with tool.exe) does absolutely nothing to fix the issues. After implementing command lists BSP detection (https://github.com/Kavawuvi/Invader/commit/3631ebb9c751dee0947bfbe0aba509fc5af79757) I noticed that the sleeping grunts are now removed. That said, when watching the cutscene using the debug camera, they are teleported out of the room instead of actually running out of the room into the door. Also, once you exit the pelican, the door opens automatically as expected, but the elite stays in the hallway.

From the looks of things, this elite not running outside may be a firing position issue.

**Comment by Kavawuvi** [comment]
Most of these have been resolved. The remaining notable issue is with the marine who doesn't say "Better follow me" in a10.map and now, rather than standing in place, skips his line and runs towards the bridge (he works correctly after this).

**Comment by Kavawuvi** [comment]
Everything mentioned above is fixed! Yay!
