### ISSUE TITLE
Preserve file timestamps in invader-archive

### ISSUE THREAD

**Issue by Vaporeon** [Kavawuvi/invader#47]
Currently `invader-archive` does not save timestamps in the created archive, so on extraction they get reset to the current time.

Timestamps can be handy to keep, for instance sometimes you might not be sure what you edited last and how long ago. One trick is to use something like `find tags -type f -printf "%T@ %Tc %p\n" | sort -n` to figure out when things were last changed.

**Comment by Kavawuvi** [comment]
This is possible to do, but given each filesystem behaves differently in how it works with time stamps, doing this will, surprisingly, not be trivial.

**Comment by Vaporeon** [comment]
https://linux.die.net/man/2/stat might be useful, using the provided modification time.

**Comment by Kavawuvi** [comment]
Done in https://github.com/Kavawuvi/invader/commit/48e413921d56b483651eff5653342d2afabeab58 (Unix-like `stat()`) and https://github.com/Kavawuvi/invader/commit/b6b9a3a37899ce52de22f99ba1751c16c8fc8823 (Windows API `stat()`)

**Comment by Kavawuvi** [comment]
In the future, it may be better to use the `std::filesystem` library in favor of the `stat()` function.

This function, while present in every C runtime that Invader is targeted towards, isn't in the standard library, thus it's completely implementation defined. The Windows `struct stat` is not cross-compatible with the Linux `struct stat` due to different member names and types, thus I have to use an `#ifdef _WIN32` for it. This isn't a big deal, but it is better to use standard library functions when possible.

https://github.com/Kavawuvi/invader/blob/b6b9a3a37899ce52de22f99ba1751c16c8fc8823/src/archive/archive.cpp#L266-L271
