### ISSUE TITLE
Add support for real filesystem paths to tags or data input

### ISSUE THREAD

**Issue by Vaporeon** [Kavawuvi/invader#52]
Currently the tools work the same was as Halo CE's tool.exe in that all paths need to be relative to the data or tags folder the content in contained in.

While fine for most usage, an annoyance with this are that bash completion can not be used on input files. Another annoyance is that if you wish to use some automated script to work with multiple arbitrary files, say with `find` for example you would first need to change returned file system paths to be relative as what the tools expect.

I nice way to handle this would be to have an argument that instead changes input to be treated as explicit paths.

As for the problem of knowing where the content should exist in the tag tree, you could simply compare the given input path to the path(s) used for tags and data. since the input path once fully expanded must contain the full tag or data path with in it, anything after that would then be the tag tree path. Also if the tag/data path does not exist in the given input path you should get told to go away.

**Comment by Kavawuvi** [comment]
Here is what I am planning on doing.

For programs that convert data into tags, the user should either give a Halo tag path (using system-native directory separators, e.g. `levels/test/tutorial/tutorial`) or a filesystem path to the data file (e.g. `data/levels/test/tutorial/tutorial.png`). The reason to not use a tag path in this case is because you are converting a file to another file, and I have never seen any sane command-line conversion program assume the path of the file you're converting using just the path of the output file.

This non-exhaustive list of programs should do this:
- invader-bitmap
- invader-font
- invader-string
- Sound tag converters
- BSP tag converters

Next, for programs that modify existing tags rather than completely overwrite the tags, the user should give either a Halo tag path (again, using native directory separators) or a filesystem path to the tag file (e.g. `levels/test/tutorial/tutorial`) or a filesystem path to the tag file (e.g. `tags/levels/test/tutorial/tutorial.bitmap`).

This non-exhaustive list of programs should do this:
- invader-archive
- invader-build
- invader-dependency
- invader-indexer
- invader-scenario
- invader-script (yes, it uses the data folder, but it's putting data into a scenario tag rather than completely remaking the scenario tag)
- Deprotectors
- Extractors (yes, it uses the data folder, but it's not getting the data from the data folder to put... in the data folder)
- GUI tag editors
    - opening specific files via dragging and dropping from a file explorer uses absolute paths
    - opening files from a tag directory browser uses Halo tag paths
    - opening tags via another tag's dependencies uses Halo tag paths

Note that when a filesystem path is given, it can be either an absolute path or a relative path.

Also note that it is possible for a relative path and a Halo tag path to be the same but they lead to different tags. For example:
- You are CD'd into a directory that has a `levels/test/tutorial/tutorial.scenario` file
- A tags directory, `/path/to/tags`, also has a `levels/test/tutorial/tutorial.scenario`
- You try to use `invader-dependency -t /path/to/tags levels/test/tutorial/tutorial.scenario`

Therefore, any time you give a path, the Halo path should be checked before it tries to use the system path, and if so, it should prefer that path.

**Comment by Kavawuvi** [comment]
I've gone ahead and started this. I'll be sure update this list as I finish everything.
- [X] [invader-archive](https://github.com/Kavawuvi/invader/commit/5e69774f0874bce943e2d79429ca5fa0c485e437)
- [ ] invader-bitmap
- [X] [invader-build](https://github.com/Kavawuvi/invader/commit/17f8f86a5e813b7c5266cf6bc57481e98de63b35)
- [X] [invader-dependency](https://github.com/Kavawuvi/invader/commit/4a9751a86cb7590c91142105ddad0f555575fcae)
- [ ] invader-font
- [ ] invader-string

**Comment by Kavawuvi** [comment]
I've gone ahead and started adding in support for this feature. I'll be sure update this list as I finish everything.
- [x] [invader-archive](https://github.com/Kavawuvi/invader/commit/5e69774f0874bce943e2d79429ca5fa0c485e437)
- [ ] invader-bitmap
- [X] [invader-build](https://github.com/Kavawuvi/invader/commit/17f8f86a5e813b7c5266cf6bc57481e98de63b35)
- [X] [invader-dependency](https://github.com/Kavawuvi/invader/commit/4a9751a86cb7590c91142105ddad0f555575fcae)
- [ ] invader-font
- [ ] invader-string

**Comment by Kavawuvi** [comment]
As of https://github.com/Kavawuvi/invader/commit/43aa04f4b152382e285bd4c0c2af43f6e796b450, all programs that take tag paths now support filesystem paths.

**Comment by Kavawuvi** [comment]
Reopened - forgot to have it add an argument to choose between paths.

**Comment by Kavawuvi** [comment]
Done as of https://github.com/Kavawuvi/invader/commit/354a341c4bf8c1c47dbbcfdd6cab6fed09b1b04a
