### ISSUE TITLE
[invader-build] Light fixtures sometimes incorrectly show interactive HUD text when a player is nearby

### ISSUE THREAD

**Issue by Vaporeon** [Kavawuvi/invader#76]
On the stock bungie map "carousel", the spotlight objects show the HUD text `Press "E" to touch <need a string entry here>` This does not happen if the map is built with tool.exe.

It also seems to be related to the original HEK tag for this object, an extracted tag works as expected so tool must default something on map build.

**Comment by Kavawuvi** [comment]
This was due to the fact that invader-build was not setting the object type to the actual light fixture index.

It appears that this tag is quite old, thus the object type in it does not correspond to a light_fixture anymore since Bungie added more object tag classes to the game. As a result, the object type value in the HEK tag is actually what device_control's value is supposed to be. This issue is similar to when some shaders were crashing the game, since the shader type wasn't correct.

The rewrite of invader-build has already correctly changed this value.

**Comment by Kavawuvi** [comment]
I've fixed the issue in older invader-build in https://github.com/Kavawuvi/invader/commit/7e7b98b31dd8254f92713ce8f795079a241501d6 so this can be closed, at least.
